### PR TITLE
Please Tell if any more changes needed!!!

### LINKED ISSUE #4: change the background with a beautiful gradient
you can change font colors according to your gradient color

### PR DESCRIPTION
**Pull request by cyber-venom003**
__ISSUENUMBER 4__

Fixes #4

#### Short description of what this resolves:
Added a radial gradient color to background which matches with the image

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by om1621** [comment]
have you changed code directly from github or using a text - editor and then pushed it ?

**Comment by om1621** [comment]
give me the live link of your repo , are u familiar with hoe to set up a live link ?

**Comment by om1621** [comment]
Resolve the merge conflicts

**Comment by cyber-venom003** [comment]
> have you changed code directly from github or using a text - editor and then pushed it ?

>Sir, I've used a text-editor to edit all files locally

**Comment by cyber-venom003** [comment]
> Resolve the merge conflicts

Done Sir...

**Comment by cyber-venom003** [comment]
> give me the live link of your repo , are u familiar with hoe to set up a live link ?



> give me the live link of your repo , are u familiar with hoe to set up a live link ?

https://github.com/cyber-venom003/interactive-map.git
I hope this works!!!

**Comment by om1621** [comment]
To create a live link just change ur repo name to given format -> ur username.github.io
And then ping me

**Comment by thesmallstar** [comment]
Write issue number in PR details, You just kept it ISSUENUMBER, you can edit it now.

**Comment by cyber-venom003** [comment]
ISSUENUMBER 4

Fixes #4

Short description of what this resolves:
Added a radial gradient color to background which matches with the image

Changes proposed in this pull request and/or Screenshots of changes:

**Comment by cyber-venom003** [comment]
> To create a live link just change ur repo name to given format -> ur username.github.io
> And then ping me

cyber-venom003.github.io

**Pull request closed without merging**
