### PR TITLE
Center aligned the elements

### LINKED ISSUE #1: center align all the content and align list items horizontally

### PR DESCRIPTION
**Pull request by sarthakm21**
__1__
Fixes #1 
Center aligns all list items, headings and image

### CODE REVIEW

**Comment by om1621** [comment]
can u provide me the live link of your repo? do u know how to create a live link ?

**Comment by sarthakm21** [comment]
@om1621 no sir

**Comment by om1621** [comment]
its simple just rename your repo  in given format   -> your username.github.io 
when u are done ping me

**Comment by sarthakm21** [comment]
@om1621 https://sarthakm21.github.io/

**Comment by sarthakm21** [comment]
this is the website

**Comment by om1621** [comment]
well done man :)

**Pull request merged**
