### PR TITLE
Please check for the side-arrow hover effect on buttons!!

### LINKED ISSUE #2: give list items a button like look with a good hover effect

### PR DESCRIPTION
**Pull request by cyber-venom003**
__2__ 

Fixes #2 

#### Short description of what this resolves:
Added buttons with a side-arrow hover effect!!

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by om1621** [comment]
effect is good :) . Additionally make the buttons horizontally aligned , remove bullets from list-items and remove blue outline that appears when a button is clicked

**Comment by cyber-venom003** [comment]
> effect is good :) . Additionally make the buttons horizontally aligned , remove bullets from list-items and remove blue outline that appears when a button is clicked

@om1621 We try it sir...

**Comment by om1621** [comment]
is there any problem ?

**Comment by cyber-venom003** [comment]
> is there any problem ?

Not yet...
Just asking can I use Bootstrap??

**Comment by om1621** [comment]
yes

**Comment by cyber-venom003** [comment]
Sir, please check my PR for this updated task....

**Comment by om1621** [comment]
provide a live link :)

**Comment by cyber-venom003** [comment]
> provide a live link :)

cyber-venom003.github.io

**Comment by om1621** [comment]
reduce the spacing btwn buttons and give a proper bottom margin to heading ( increase font-size of heading) and remove the blue outline.

**Comment by cyber-venom003** [comment]
> reduce the spacing btwn buttons and give a proper bottom margin to heading ( increase font-size of heading) and remove the blue outline.

Sir, can I do it without using list???

**Comment by om1621** [comment]
ok

**Comment by cyber-venom003** [comment]
@om1621 Sir, please check for this commit. I hope this should work well!! :+1:

**Comment by om1621** [comment]
well done man 👍

**Comment by cyber-venom003** [comment]
> well done man +1

Thank You Sir, But my score in leaderboard hasn't been updated for this issue....

**Pull request merged**
