### PR TITLE
Added A Beautiful Gradient 

### LINKED ISSUE #4: change the background with a beautiful gradient
you can change font colors according to your gradient color

### PR DESCRIPTION
**Pull request by cyber-venom003**
__4__ 

Fixes #4 

#### Short description of what this resolves:
Added A Beautiful gradient matching with image.

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by cyber-venom003** [comment]
@om1621 Live Link: cyber-venom003.github.io
@om1621 Sir, There is a small problem!! My live link is not working exactly in that same way that it works on my PC!!

**Comment by om1621** [comment]
have u pushed your latest changes ?

**Comment by cyber-venom003** [comment]
> have u pushed your latest changes ?

Yes Sir....
Please check it by cloning it into a local device

**Comment by om1621** [comment]
I cloned your repo and checked it locally , there is no difference from link one but no problem :) gradient is looking well

**Pull request merged**
